# Generated by Django 4.1.2 on 2022-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0002_remove_video_create_at_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m%d'),
        ),
    ]
