# Generated by Django 4.1.2 on 2022-10-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0004_alter_video_file_alter_video_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created_at',)},
        ),
    ]
