# Generated by Django 4.1.2 on 2022-10-12 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('video_hosting', '0008_video_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image/profile/image/%Y/%m/')),
                ('banner', models.ImageField(null=True, upload_to='image/profile/banner/%Y/%m/')),
                ('logo', models.ImageField(null=True, upload_to='image/profile/logo/%Y/%m/')),
            ],
        ),
    ]
