# Generated by Django 4.1.2 on 2022-10-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0009_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video_hosting.channel', verbose_name='Канал'),
            preserve_default=False,
        ),
    ]
