# Generated by Django 4.1.2 on 2022-10-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0010_remove_video_user_video_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='owner',
            new_name='channel',
        ),
    ]
