# Generated by Django 4.1.2 on 2022-10-13 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_hosting', '0011_rename_owner_video_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Channel Name', max_length=40),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email', models.BooleanField(default=0)),
                ('is_block', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
